# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SwiftContent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod ‘Alamofire’
pod 'Kingfisher'
pod 'SnapKit'
pod "SwiftyJSON"
pod "MJRefresh"
pod "FDFullscreenPopGesture"
pod 'MBProgressHUD'
pod 'MLInputDodger'
  # Pods for SwiftContent

  target 'SwiftContentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftContentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
